---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: pre-commit tests


on:
  pull_request_target:
  workflow_call:
    inputs:
      collection_namespace:
        description: "Install collection python dependencies"
        required: true
        type: string
      collection_name:
        description: "Path to the collection source"
        required: true
        type: string
      collection_version:
        description: The final collection path
        required: false
        type: string
      collection_repo:
        description: The collection url
        required: false
        type: string
    secrets:
      ansible_ah_token:
        description: API key for galaxy
        required: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: pip install --upgrade "ansible-core>=2.15,<2.19" pyyaml==6.0.1
      - name: Install collection
        run: ansible-galaxy collection install . -vvvv
        shell: bash
        env:
          ANSIBLE_GALAXY_SERVER_VALIDATED_URL: 'https://console.redhat.com/api/automation-hub/content/validated/'
          ANSIBLE_GALAXY_SERVER_VALIDATED_TOKEN: ${{ secrets.ansible_ah_token}}
          ANSIBLE_GALAXY_SERVER_VALIDATED_AUTH_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          ANSIBLE_GALAXY_SERVER_PUBLISHED_URL: 'https://console.redhat.com/api/automation-hub/content/published/'
          ANSIBLE_GALAXY_SERVER_PUBLISHED_TOKEN: ${{ secrets.ansible_ah_token }}
          ANSIBLE_GALAXY_SERVER_PUBLISHED_AUTH_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          ANSIBLE_GALAXY_SERVER_COMMUNITY_URL: 'https://galaxy.ansible.com/'
          ANSIBLE_GALAXY_SERVER_LIST: 'published, validated, community'
      - uses: pre-commit/action@v3.0.1
...
