---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: pre-commit tests

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: pip install --upgrade ansible-core pyyaml==6.0.1
      - name: Install collection
        run: ansible-galaxy collection install . --no-deps
      - uses: pre-commit/action@v3.0.1
...
