---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: pre-commit tests


on:
  workflow_call:

jobs:
  pre-commit:
    uses: "redhat-cop/ansible_collections_tooling/.github/workflows/pre-commit_crc.yml@main"
  build-import:
    uses: ansible/ansible-content-actions/.github/workflows/build_import.yaml@main
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.mlc_config.json'
  all_green:
    if: ${{ always() }}
    needs:
      - pre-commit
      - build-import
      - markdown-link-check
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.pre-commit.result }}',
          '${{ needs.build-import.result }}',
          '${{ needs.markdown-link-check.result }}',
          ]) == {'success'}"
...
