---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  workflow_call:
    inputs:
      collection_namespace:
        description: First namespace to push to as in 'infra'
        required: true
        type: string
      collection_name:
        description: "Path to the collection source"
        required: true
        type: string
      collection_version:
        description: The final collection path
        required: false
        type: string
      collection_repo:
        description: The collection url
        required: false
        type: string
      quay_username:
        description: "username/namespace to upload the EE to"
        required: true
        type: string
      collection_dependencies:
        description: The collection dependencies (as a space separated list)
        required: false
        type: string
    secrets:
      galaxy_api_key:
        description: API key for galaxy
        required: true
      token:
        description: token for uploading tarballs to a release
        required: true
      quay_token:
        description: token for quay
        required: true

jobs:
  pre-commit:
    uses: redhat-cop/ansible_collections_tooling/.github/workflows/pre-commit.yml@main
    with:
      collection_namespace: ${{ inputs.collection_namespace }}
      collection_name: ${{ inputs.collection_name }}
      collection_version: ${{ inputs.collection_version }}
      collection_repo: ${{ inputs.collection_repo }}
      collection_dependencies: ${{ inputs.collection_dependencies }}
  sanity:
    uses: redhat-cop/ansible_collections_tooling/.github/workflows/sanity.yml@main
    with:
      collection_namespace: ${{ inputs.collection_namespace }}
      collection_name: ${{ inputs.collection_name }}
      collection_version: ${{ inputs.collection_version }}
      collection_repo: ${{ inputs.collection_repo }}
      collection_dependencies: ${{ inputs.collection_dependencies }}
  prechecks:
    needs:
      - pre-commit
      - sanity
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.pre-commit.result }}',
          '${{ needs.sanity.result }}',
          ]) == {'success'}"
  infra_release:
    needs:
      - prechecks
    uses: redhat-cop/ansible_collections_tooling/.github/workflows/release.yml@main
    with:
      collection_namespace: ${{ inputs.collection_namespace }}
      collection_name: ${{ inputs.collection_name }}
      collection_version: ${{ inputs.collection_version }}
      collection_repo: ${{ inputs.collection_repo }}
    secrets:
      api_key: ${{ secrets.galaxy_api_key }}
      token: ${{ secrets.token }}
  deployEE:
    needs:
      - infra_release
    uses: redhat-cop/ansible_collections_tooling/.github/workflows/build_ee.yml@main
    with:
      quay_username: ${{ inputs.quay_username }}
    secrets:
      quay_token: ${{ secrets.quay_token }}
  changelog:
    needs:
      - infra_release
    uses: redhat-cop/ansible_collections_tooling/.github/workflows/create_changelog.yml@main
    with:
      collection_namespace: ${{ inputs.collection_namespace }}
      collection_name: ${{ inputs.collection_name }}
      collection_version: ${{ inputs.collection_version }}
      collection_repo: ${{ inputs.collection_repo }}
    secrets:
      token: ${{ secrets.token }}
...
